### ISSUE TITLE
Not exactly an issue, just a little tip.

### ISSUE THREAD

**Issue by vollmann-ariel** [vc1492a/Raspberry-Pi-Fan-Control#2]
![GPIO-Pinout-Diagram-2](https://user-images.githubusercontent.com/44172039/81477146-84877280-91ec-11ea-8201-94588f9ba842.png)
Excellent idea, however, the transistor is not being used most efficiently. The emitter follower configuration to handle loads dissipates more power by having a greater voltage drop between the collector and the emitter. And connecting its base directly to a RaspberryPi pin you run an extra risk in case of a burnt transistor.
You should saturate it using a configuration like the one shown [here](https://www.electronics-tutorials.ws/transistor/tran_4.html) (go to "Digital Logic Transistor Switch").
This way:
- You get total protection by putting an extra (let's say 33kOhm) resistor between the transistor base and the GPIO pin.
- You've got almost-zero power dissipation on the transistor itself.
- You source the full 5 volts to the fan (full speed) with no voltage drop on the transistor.

Thanks!

**Comment by vc1492a** [comment]
Thanks @vollmann-ariel for opening this issue and providing a nice level of detail! Good suggestion. It may be nice to include a set of wiring diagrams in the repository (in a directory called `wiring_diagrams`) and point users there from `readme.md` instead of simply showing them the wiring diagram that's there now. 

@vollmann-ariel have you tried out the above configuration yourself? Happy to include it if we can confirm it works (I have no reason not to believe it does, just double checking).

**Comment by vollmann-ariel** [comment]
@vc1492a I'm new at GitHub, I've tried unsuccessfully to create a folder un your repo but I've noticed I can edit the `readme.md` file and reference the proposed circuit if you will.
Below is the final resistor value I tried, 33k proved to be too high to saturate the transistor (I forgot that the Raspi output high state is only 3,3V also and the transistor has low hFE).
NOTE: You can lower the resistor value down to 3k or even 1k without exceeding the GPIO current limit. The criteria to use is to measure the collector to emitter voltage drop: It should be around 0.1Volts, and lower the resistor value if it's way over that 0.1 V. Anyway 4k7 should do the job for those small fans.
Sorry for the inconvenience, Valentino. I'll try to read _GitHub for dummies_ next time!
![Circuit](https://user-images.githubusercontent.com/44172039/81510426-001a1a00-92e8-11ea-87c9-34183839e74f.png)

**Comment by vc1492a** [comment]
Hi @vollmann-ariel, no worries! In the future, feel free to submit a pull request - that would be the best way to integrate your suggestions! 

Thanks for the updated reply. I have updated `readme.md` to include some information on the additional diagram, and have updated the code as well to include some additional docstring and type hints which were introduced in Python 3.5. 

Cheers!
