### ISSUE TITLE
Not an issue, but a question.

### ISSUE THREAD

**Issue by kc-nj** [vc1492a/Raspberry-Pi-Fan-Control#3]
Greetings, newer Pi user here. 

I'm running Linux 10 (Buster) on a Pi 3B V1.2. In Pi Configuration > Performance there's now an option to enable a fan, the GPIO and temp to trigger the fan. That would be the same (but easier) than writing the script, correct?

From my research, it seems that was added for a three wire fan (Power, Ground, Control); so if I am using standard two wire fans, I would still need to add the transistor, correct? 

Second question, any problems running two 5V 0.2amp fans off of the one transistor? If so, what if I run them off of the 3.3V instead?

**Comment by vc1492a** [comment]
Hey @kc-nj! Happy to hear the resources I put together are useful to you. 

When I wrote the script, an option to enable a fan wasn't available. I also use distros outside of Raspbian from time to time which do not have a fan enabling option, so the script is still very useful in that case. 

I'm not an electrical engineer, but from my understanding you would still need the transistor, yes. I don't think you would have trouble with one transistor, but I don't have enough subject matter knowledge to let you know definitively, sorry!

**Comment by kc-nj** [comment]
Thank you for responding. 

I assumed that feature was not available at the time you wrote the script.

**Comment by vc1492a** [comment]
Gotcha! Yes exactly. Best of luck!
